export const ACTIONS = {
  SET_MODAL_VISIBILITY: 'SET_MODAL_VISIBILITY',
  SET_SELECTED_CONTACT: 'SET_SELECTED_CONTACT',
  SET_STORE: 'SET_STORE',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  UPDATE_CONTACT_METHOD: 'UPDATE_CONTACT_METHOD'
};
