export const ACTIONS = {
  SET_MODAL_VISIBILITY: 'SET_MODAL_VISIBILITY',
  SET_SELECTED_CONTACT: 'SET_SELECTED_CONTACT',
  SET_CONTACTS: 'SET_CONTACTS',
  SET_ROTATIONS: 'SET_ROTATIONS',
  SET_EVENTS: 'SET_EVENTS',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  UPDATE_CONTACT_METHOD: 'UPDATE_CONTACT_METHOD',
  SET_USER: 'SET_USER'
};
